/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LaporanRouteImport } from './routes/laporan'
import { Route as DonaturRouteImport } from './routes/donatur'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ZzzIndexRouteImport } from './routes/zzz/index'
import { Route as MainIndexRouteImport } from './routes/main/index'
import { Route as ZzzMainIndexRouteImport } from './routes/zzz/main/index'
import { Route as ZzzMainSettingRouteImport } from './routes/zzz/main/setting'

const LaporanRoute = LaporanRouteImport.update({
  id: '/laporan',
  path: '/laporan',
  getParentRoute: () => rootRouteImport,
} as any)
const DonaturRoute = DonaturRouteImport.update({
  id: '/donatur',
  path: '/donatur',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ZzzIndexRoute = ZzzIndexRouteImport.update({
  id: '/zzz/',
  path: '/zzz/',
  getParentRoute: () => rootRouteImport,
} as any)
const MainIndexRoute = MainIndexRouteImport.update({
  id: '/main/',
  path: '/main/',
  getParentRoute: () => rootRouteImport,
} as any)
const ZzzMainIndexRoute = ZzzMainIndexRouteImport.update({
  id: '/zzz/main/',
  path: '/zzz/main/',
  getParentRoute: () => rootRouteImport,
} as any)
const ZzzMainSettingRoute = ZzzMainSettingRouteImport.update({
  id: '/zzz/main/setting',
  path: '/zzz/main/setting',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/donatur': typeof DonaturRoute
  '/laporan': typeof LaporanRoute
  '/main': typeof MainIndexRoute
  '/zzz': typeof ZzzIndexRoute
  '/zzz/main/setting': typeof ZzzMainSettingRoute
  '/zzz/main': typeof ZzzMainIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/donatur': typeof DonaturRoute
  '/laporan': typeof LaporanRoute
  '/main': typeof MainIndexRoute
  '/zzz': typeof ZzzIndexRoute
  '/zzz/main/setting': typeof ZzzMainSettingRoute
  '/zzz/main': typeof ZzzMainIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/donatur': typeof DonaturRoute
  '/laporan': typeof LaporanRoute
  '/main/': typeof MainIndexRoute
  '/zzz/': typeof ZzzIndexRoute
  '/zzz/main/setting': typeof ZzzMainSettingRoute
  '/zzz/main/': typeof ZzzMainIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/donatur'
    | '/laporan'
    | '/main'
    | '/zzz'
    | '/zzz/main/setting'
    | '/zzz/main'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/donatur'
    | '/laporan'
    | '/main'
    | '/zzz'
    | '/zzz/main/setting'
    | '/zzz/main'
  id:
    | '__root__'
    | '/'
    | '/donatur'
    | '/laporan'
    | '/main/'
    | '/zzz/'
    | '/zzz/main/setting'
    | '/zzz/main/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DonaturRoute: typeof DonaturRoute
  LaporanRoute: typeof LaporanRoute
  MainIndexRoute: typeof MainIndexRoute
  ZzzIndexRoute: typeof ZzzIndexRoute
  ZzzMainSettingRoute: typeof ZzzMainSettingRoute
  ZzzMainIndexRoute: typeof ZzzMainIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/laporan': {
      id: '/laporan'
      path: '/laporan'
      fullPath: '/laporan'
      preLoaderRoute: typeof LaporanRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/donatur': {
      id: '/donatur'
      path: '/donatur'
      fullPath: '/donatur'
      preLoaderRoute: typeof DonaturRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/zzz/': {
      id: '/zzz/'
      path: '/zzz'
      fullPath: '/zzz'
      preLoaderRoute: typeof ZzzIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/main/': {
      id: '/main/'
      path: '/main'
      fullPath: '/main'
      preLoaderRoute: typeof MainIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/zzz/main/': {
      id: '/zzz/main/'
      path: '/zzz/main'
      fullPath: '/zzz/main'
      preLoaderRoute: typeof ZzzMainIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/zzz/main/setting': {
      id: '/zzz/main/setting'
      path: '/zzz/main/setting'
      fullPath: '/zzz/main/setting'
      preLoaderRoute: typeof ZzzMainSettingRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DonaturRoute: DonaturRoute,
  LaporanRoute: LaporanRoute,
  MainIndexRoute: MainIndexRoute,
  ZzzIndexRoute: ZzzIndexRoute,
  ZzzMainSettingRoute: ZzzMainSettingRoute,
  ZzzMainIndexRoute: ZzzMainIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
